nname: Run Naukri Resume Test Daily

on:
  schedule:
    - cron: '55 3 * * *' # Runs daily at 9:25 AM IST (3:55 AM UTC)
  workflow_dispatch:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '17'

    - name: Set up Chrome for Selenium
      uses: browser-actions/setup-chrome@v4

    - name: Build with Maven
      run: mvn clean install

    - name: Run tests
      run: |
        echo "Running Naukri Resume Update Automation..."
        mvn test

    - name: Create dummy test-output folder if missing
      if: failure()
      run: mkdir -p test-output

    - name: Archive test results
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: test-results
        path: test-output/
